name: zerotrust_fitness
description: A new Nowa project.
publish_to: none
version: 0.0.1+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nowa_runtime: ^0.1.3
  provider: 6.1.5
  shared_preferences: 2.5.3
  dio: 5.5.0+1
  go_router: 17.0.1
  supabase_flutter: 2.9.0
  riverpod: 3.0.0
  riverpod_annotation: 3.0.0
  cryptography_flutter: 2.3.4
  sqlcipher_flutter_libs: 0.6.4
  drift: ^2.31.0
  health: 13.1.4
  cryptography: 2.8.1
  flutter_secure_storage: 9.2.2
  flutter_dotenv: 5.1.0
  workmanager: 0.8.0
  home_widget: 0.8.0
  fl_chart: 1.0.0
  shimmer: 3.0.0
  flutter_riverpod: 3.0.0
  local_auth: 2.3.0
  path_provider: 2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
